Environment: "localhost"
Logger:
  Level: "debug"
HttpServer:
  Port: 8080
Database:
  Host: "localhost"
  Port: 8185
  User: "test"
  DbName: "tododb"
  Password: ""
  Tables: [ "todo" ]
  CreateTable: true